game:
  arch: win64
  exe: drive_c/Program Files (x86)/cemu_1.11.4/Cemu.exe
  prefix: /home/bradyn/Games/cemu
system:
  env:
    __GL_THREADED_OPTIMIZATIONS: '1'
wine:
  overrides:
    dbghelp: native,builtin
  version: 3.1-x86_64
