game:
  exe: /home/bradyn/.wine/drive_c/Program Files (x86)/StandingStoneGames/Dungeons
    & Dragons Online/TurbineLauncher.exe
system: {}
wine:
  Desktop: true
  OffscreenRenderingMode: backbuffer
  WineDesktop: 2400x1600
