game:
  exe: /home/bradyn/.wine/drive_c/Program Files/StandingStoneGames/Dungeons & Dragons
    Online (Preview)/TurbineInvoker.exe
system: {}
wine:
  Desktop: true
  MouseWarpOverride: force
  WineDesktop: 2400x1600
