game:
  exe: /home/bradyn/.wine/drive_c/Program Files/StandingStoneGames/Dungeons & Dragons
    Online/TurbineLauncher.exe
system:
  display: 'off'
  reset_desktop: false
wine:
  Desktop: false
  MouseWarpOverride: force
  OffscreenRenderingMode: fbo
  UseGLSL: enabled
  WineDesktop: 2400x1600
