game:
  exe: /home/bradyn/Games/DDO/TurbineLauncher.exe
  prefix: ''
system:
  disable_runtime: false
  display: 'off'
wine:
  Desktop: true
  MouseWarpOverride: disable
  WineDesktop: 2560x1080
  version: staging-3.5-x86_64
