game:
  arch: win64
  exe: /home/bradyn/Games/Ori and the Blind Forest/oriDE.exe
  prefix: ~/Games/DXVK
system:
  disable_runtime: true
wine:
  Desktop: true
  WineDesktop: 2560x1080
  dumbxinputemu: true
  version: system
  x360ce-xinput9: false
