game:
  arch: win64
  args: battlenet://Pro/
  exe: drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe
  prefix: /home/bradyn/Games/overwatch
system:
  env:
    __GL_SHADER_DISK_CACHE: '1'
    __GL_SHADER_DISK_CACHE_PATH: /home/bradyn/Games/overwatch
    __GL_THREADED_OPTIMIZATIONS: '1'
    mesa_glthread: 'true'
  exclude_processes: Agent.exe
wine:
  version: staging-3.5-x86_64
