game:
  arch: win64
  exe: /home/bradyn/Games/StarCraft II/StarCraft II.exe
  prefix: /home/bradyn/Games/starcraft-ii
system:
  disable_runtime: true
  env:
    __GL_SHADER_DISK_CACHE: '1'
    __GL_SHADER_DISK_CACHE_PATH: /home/bradyn/Games/starcraft-ii
    __GL_THREADED_OPTIMIZATIONS: '1'
    mesa_glthread: 'true'
wine:
  Desktop: false
  MouseWarpOverride: enable
  OffscreenRenderingMode: fbo
  UseGLSL: enabled
  WineDesktop: 1600x900
  version: pba-3.3-x86_64
