# dropbearkey
# Autogenerated from man page /usr/share/man/man1/dropbearkey.1.gz
complete -c dropbearkey -s t --description 'Type of key to generate.  Must be one of  rsa  ecdsa or R dss .'
complete -c dropbearkey -s f --description 'Write the secret key to the file file.  For client authentication ~/.'
complete -c dropbearkey -s s --description 'Set the key size to  bits bits, should be multiple of 8 (optional).'
complete -c dropbearkey -s y --description 'Just print the publickey and fingerprint for the private key in file.'

