# fbgs
# Autogenerated from man page /usr/share/man/man1/fbgs.1.gz
complete -c fbgs -s h -l help --description 'Print usage info (overwrites fbi option).'
complete -c fbgs -s b -l bell --description 'Emit a beep when the document is ready.'
complete -c fbgs -s c -l color --description 'To render the pages in color (default is N&B).'
complete -c fbgs -s l --description 'To get the pages rendered with 100 dpi (default is 75).'
complete -c fbgs -o xl --description 'To get the pages rendered with 120 dpi.'
complete -c fbgs -o xxl --description 'To get the pages rendered with 150 dpi.'
complete -c fbgs -s r -l resolution --description 'To get the pages rendered with n dpi (overwrites fbi option).'
complete -c fbgs -o fp -l firstpage --description 'Begins interpreting on the designated page of the document.'
complete -c fbgs -o lp -l lastpage --description 'Stops interpreting after the designated page of the document.'
complete -c fbgs -s p -l password --description 'You can use this option if your PDF file requires a password.'

