# KateDJ
# Autogenerated from man page /usr/share/man/man1/KateDJ.1.gz
complete -c KateDJ -s h --description 'Show command line help.'
complete -c KateDJ -s V --description 'Show version information.'

